theme: jekyll-theme-slate
title: Generate XboxEra leaderboard
description: tools for generating the weekly and monthly leaderboards on XboxEra
show_downloads: "true"

github:
  zip_url: https://github.com/nullicw/xboxera-leaderboard/releases/download/v1.0.1/xboxera-leaderboard-win-x86.zip
