name: .NET publish

on:
  push:
    # tags: releases/[1-9]+.[0-9]+.[0-9]+
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'
        dotnet-quality: 'preview'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish win-x86
      run: dotnet publish --configuration Release --framework net6.0 --output ./publish --runtime win-x86 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=Link -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: xboxera-leaderboard-win-x86
        path: ./publish
    - name: Zip
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r xboxera-leaderboard-win-x86.zip ./publish
    - name: Add release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: xboxera-leaderboard-win-x86.zip
