name: Generate weekly leaderboard

on:
  schedule:
    # every week 06:20 AM UTC on Monday (https://crontab.guru/#20_6_*_*_1)
    - cron:  '20 6 * * 1'
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Generate weekly leaderboard
      run: dotnet run --configuration Release --weekly ./docs/scores
    - name: checkin new stats
      uses: EndBug/add-and-commit@v7
      with:
        message: 'weekly run'
